# Generated by Django 5.1.7 on 2026-05-19 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_client_location_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='🏆', max_length=10)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ClientCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('phone2', models.CharField(blank=True, default='', max_length=20)),
                ('address', models.TextField(blank=True, default='')),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientVIPLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('min_orders', models.IntegerField(default=0)),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cashback_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('color', models.CharField(default='#cd7f32', max_length=20)),
            ],
            options={
                'ordering': ['min_orders'],
            },
        ),
        migrations.CreateModel(
            name='ClientDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('remaining', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.CharField(choices=[('active', 'Faol'), ('partial', 'Qisman'), ('paid', "To'langan"), ('written_off', 'Hisobdan chiqarildi')], default='active', max_length=15)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='client_erp.clientcustomer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientDebtPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('payment_method', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('transfer', "O'tkazma")], default='cash', max_length=10)),
                ('date', models.DateField()),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='client_erp.clientdebt')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ClientFinanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('income', 'Kirim'), ('expense', 'Chiqim'), ('debt_given', 'Qarz berdim'), ('debt_received', 'Qarz oldim'), ('debt_paid', "Qarz to'ladi")], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(default='UZS', max_length=5)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('amount_uzs', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('date', models.DateField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_records', to='client_erp.clientcustomer')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientFinanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Yaratildi'), ('update', "O'zgartirildi"), ('delete', "O'chirildi")], max_length=10)),
                ('old_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='client_erp.clientfinancerecord')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('in_progress', 'Jarayonda'), ('at_mebelcity', 'MebelCity da'), ('ready', 'Tayyor'), ('delivered', 'Topshirildi'), ('cancelled', 'Bekor')], default='new', max_length=20)),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('mebelcity_order_id', models.IntegerField(blank=True, null=True)),
                ('mebelcity_tenant', models.CharField(blank=True, default='', max_length=50)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='client_erp.clientcustomer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='clientfinancerecord',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_records', to='client_erp.clientorder'),
        ),
        migrations.AddField(
            model_name='clientdebt',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_erp.clientorder'),
        ),
        migrations.CreateModel(
            name='ClientOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('material', models.CharField(blank=True, default='', max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('unit', models.CharField(default='dona', max_length=20)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='client_erp.clientorder')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ClientOrderPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='client_erp/orders/')),
                ('caption', models.CharField(blank=True, default='', max_length=200)),
                ('stage', models.CharField(choices=[('before', 'Oldin'), ('during', 'Jarayon'), ('after', 'Keyin')], default='during', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='client_erp.clientorder')),
            ],
        ),
        migrations.CreateModel(
            name='ClientOrderTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='client_erp.clientorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Telefon (login)')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Username')),
                ('password_hash', models.CharField(max_length=128, verbose_name='Parol (hash)')),
                ('full_name', models.CharField(max_length=200, verbose_name='Ism')),
                ('organization', models.CharField(blank=True, default='', max_length=200, verbose_name='Tashkilot')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='client_erp/avatars/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False, verbose_name='Admin tasdiqlagan')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Bloklangan')),
                ('telegram_chat_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('telegram_username', models.CharField(blank=True, default='', max_length=100)),
                ('notify_telegram', models.BooleanField(default=True)),
                ('notify_order_status', models.BooleanField(default=True)),
                ('notify_debt_reminder', models.BooleanField(default=True)),
                ('notify_deadline', models.BooleanField(default=True)),
                ('notify_daily_report', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('client', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mini_erp_user', to='clients.client', verbose_name='Katta ERP Client')),
            ],
            options={
                'verbose_name': 'Mini ERP Foydalanuvchi',
                'verbose_name_plural': 'Mini ERP Foydalanuvchilar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientPortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('panorama', '360° Panorama'), ('photo', 'Foto'), ('project', 'Loyiha')], default='photo', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('mebelcity_order_id', models.IntegerField(blank=True, null=True)),
                ('images', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='client_erp.clientuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='clientorder',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='client_erp.clientuser'),
        ),
        migrations.CreateModel(
            name='ClientNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('push', 'Push'), ('sms', 'SMS'), ('in_app', 'Tizim')], default='in_app', max_length=10)),
                ('notification_type', models.CharField(choices=[('order_status', 'Buyurtma holati'), ('debt_reminder', 'Qarz eslatma'), ('deadline_warning', 'Muddat'), ('mebelcity_update', 'MebelCity'), ('daily_report', 'Kundalik'), ('weekly_report', 'Haftalik'), ('achievement', 'Yutuq'), ('promo', 'Aksiya'), ('custom', 'Boshqa')], default='custom', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_sent', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='client_erp.clientuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='clientfinancerecord',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_records', to='client_erp.clientuser'),
        ),
        migrations.AddField(
            model_name='clientdebt',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='client_erp.clientuser'),
        ),
        migrations.AddField(
            model_name='clientcustomer',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='client_erp.clientuser'),
        ),
        migrations.CreateModel(
            name='ClientZamer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('note', models.TextField(blank=True, default='')),
                ('photos', models.JSONField(blank=True, default=list)),
                ('mebelcity_zamer_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zamers', to='client_erp.clientcustomer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zamers', to='client_erp.clientorder')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zamers', to='client_erp.clientuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientZamerRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('depth', models.IntegerField(default=0)),
                ('zamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='client_erp.clientzamer')),
            ],
        ),
        migrations.CreateModel(
            name='ClientZamerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('door', 'Eshik'), ('window', 'Deraza'), ('column', 'Ustun'), ('pipe', 'Quvur'), ('socket', 'Rozetka'), ('other', 'Boshqa')], default='other', max_length=10)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='client_erp.clientzamerroom')),
            ],
        ),
        migrations.CreateModel(
            name='ClientUserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_erp.clientachievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='client_erp.clientuser')),
            ],
            options={
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
