# Generated by Django 5.1.7 on 2026-05-20 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientviplevel',
            options={'ordering': ['level_number']},
        ),
        migrations.AddField(
            model_name='clientuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name="Tug'ilgan kun"),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='coins',
            field=models.IntegerField(default=0, verbose_name='Tanga (sarflanmagan)'),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='coins_total_earned',
            field=models.IntegerField(default=0, verbose_name="Jami yig'ilgan tanga"),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi faollik'),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='profile_completion',
            field=models.IntegerField(default=0, verbose_name="Profil to'liqligi %"),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='referral_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Tavsiya kodi'),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='referral_count',
            field=models.IntegerField(default=0, verbose_name='Tavsiya qilinganlar soni'),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='referral_earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Tavsiya komissiyasi jami (UZS)'),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='client_erp.clientuser', verbose_name='Kim tavsiya qilgan'),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='streak_days',
            field=models.IntegerField(default=0, verbose_name='Ketma-ket kun'),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='streak_last_date',
            field=models.DateField(blank=True, null=True, verbose_name='Oxirgi streak sanasi'),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='turnover_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Umumiy aylanma (UZS)'),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='turnover_year',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Yillik aylanma (UZS)'),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='vip_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='client_erp.clientviplevel', verbose_name='VIP daraja'),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='xp',
            field=models.IntegerField(default=0, verbose_name='XP (tajriba)'),
        ),
        migrations.AddField(
            model_name='clientviplevel',
            name='auto_promote',
            field=models.BooleanField(default=True, verbose_name="Avtomatik ko'tarilish"),
        ),
        migrations.AddField(
            model_name='clientviplevel',
            name='badge_icon',
            field=models.CharField(default='⭐', max_length=10, verbose_name='Emoji'),
        ),
        migrations.AddField(
            model_name='clientviplevel',
            name='badge_image',
            field=models.ImageField(blank=True, null=True, upload_to='client_erp/badges/', verbose_name='Karta dizayn rasmi'),
        ),
        migrations.AddField(
            model_name='clientviplevel',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Imtiyozlar tavsifi'),
        ),
        migrations.AddField(
            model_name='clientviplevel',
            name='downgrade_after_months',
            field=models.IntegerField(default=6, verbose_name='Faolsizlikdan keyin pasaytirish (oy)'),
        ),
        migrations.AddField(
            model_name='clientviplevel',
            name='level_number',
            field=models.IntegerField(default=1, verbose_name='Daraja raqami (1-5)'),
        ),
        migrations.AddField(
            model_name='clientviplevel',
            name='min_turnover',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Yillik min aylanma (UZS)'),
        ),
        migrations.AddField(
            model_name='clientviplevel',
            name='referral_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Tavsiya komissiyasi %'),
        ),
        migrations.AddField(
            model_name='clientviplevel',
            name='require_admin_approval',
            field=models.BooleanField(default=False, verbose_name='Admin tasdiqlashi kerak'),
        ),
        migrations.AlterField(
            model_name='clientviplevel',
            name='color',
            field=models.CharField(default='#cd7f32', max_length=20, verbose_name='Rang (HEX)'),
        ),
        migrations.AlterField(
            model_name='clientviplevel',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Chegirma %'),
        ),
        migrations.AlterField(
            model_name='clientviplevel',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Min summa (eski)'),
        ),
        migrations.AlterField(
            model_name='clientviplevel',
            name='min_orders',
            field=models.IntegerField(default=0, verbose_name='Min buyurtmalar soni'),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_type', models.CharField(choices=[('news', 'Yangilik'), ('promo', 'Aksiya'), ('discount', 'Chegirma'), ('event', "Yig'ilish/Tadbirat"), ('notification', 'Bildirishnoma')], default='news', max_length=20, verbose_name='Turi')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('body', models.TextField(verbose_name='Matn')),
                ('image', models.ImageField(blank=True, null=True, upload_to='client_erp/announcements/', verbose_name='Banner rasm')),
                ('target_all', models.BooleanField(default=True, verbose_name='Hammaga')),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Chegirma %')),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name="Chegirma (so'm)")),
                ('discount_code', models.CharField(blank=True, default='', max_length=50, verbose_name='Kupon kodi')),
                ('start_date', models.DateTimeField(verbose_name='Boshlanish')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Tugash')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Tepaga qadash')),
                ('send_telegram', models.BooleanField(default=False, verbose_name='Telegram ga yuborish')),
                ('telegram_sent', models.BooleanField(default=False, verbose_name='Yuborildi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan')),
                ('target_levels', models.ManyToManyField(blank=True, related_name='announcements', to='client_erp.clientviplevel', verbose_name='Faqat shu darajalar')),
                ('target_users', models.ManyToManyField(blank=True, related_name='targeted_announcements', to='client_erp.clientuser', verbose_name='Faqat shu foydalanuvchilar')),
            ],
            options={
                'verbose_name': "E'lon",
                'verbose_name_plural': "E'lonlar",
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, default='', verbose_name='Tavsif')),
                ('image', models.ImageField(blank=True, null=True, upload_to='client_erp/events/')),
                ('event_date', models.DateTimeField(verbose_name='Sana va vaqt')),
                ('location', models.CharField(blank=True, default='', max_length=300, verbose_name='Joy')),
                ('location_url', models.URLField(blank=True, default='', verbose_name='Xarita havolasi')),
                ('max_participants', models.IntegerField(default=0, verbose_name='Maks ishtirokchilar (0=cheksiz)')),
                ('xp_reward', models.IntegerField(default=500, verbose_name='Ishtirok uchun XP')),
                ('coin_reward', models.IntegerField(default=150, verbose_name='Ishtirok uchun tanga')),
                ('target_all', models.BooleanField(default=True, verbose_name='Hammaga')),
                ('qr_code', models.CharField(blank=True, max_length=50, unique=True, verbose_name='QR kod')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('target_levels', models.ManyToManyField(blank=True, related_name='events', to='client_erp.clientviplevel', verbose_name='Faqat shu darajalar')),
            ],
            options={
                'verbose_name': 'Tadbirat',
                'verbose_name_plural': 'Tadbiratlar',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='GamificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Kod')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, default='', verbose_name='Tavsif')),
                ('icon', models.CharField(default='⭐', max_length=10, verbose_name='Emoji')),
                ('xp_reward', models.IntegerField(default=0, verbose_name='XP mukofoti')),
                ('coin_reward', models.IntegerField(default=0, verbose_name='Tanga mukofoti')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('is_repeatable', models.BooleanField(default=True, verbose_name='Takroriy')),
                ('max_per_day', models.IntegerField(blank=True, help_text="0 yoki bo'sh = cheksiz", null=True, verbose_name='Kuniga maks')),
                ('sort_order', models.IntegerField(default=0)),
                ('min_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_erp.clientviplevel', verbose_name='Minimal daraja')),
            ],
            options={
                'verbose_name': 'Gamifikatsiya qoidasi',
                'verbose_name_plural': 'Gamifikatsiya qoidalari',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_type', models.CharField(choices=[('daily', 'Kunlik'), ('weekly', 'Haftalik'), ('onetime', 'Bir martalik'), ('seasonal', 'Mavsumiy')], default='daily', max_length=20)),
                ('title', models.CharField(max_length=200, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(default='📋', max_length=10)),
                ('xp_reward', models.IntegerField(default=0)),
                ('coin_reward', models.IntegerField(default=0)),
                ('action_type', models.CharField(choices=[('login', 'Ilovaga kirish'), ('purchase', 'Xarid qilish'), ('review', 'Sharh yozish'), ('referral', "Do'st tavsiya"), ('view_products', "Mahsulot ko'rish"), ('share', 'Ulashish'), ('custom', 'Boshqa')], default='custom', max_length=20)),
                ('action_count', models.IntegerField(default=1, verbose_name='Necha marta bajarish kerak')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('min_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_erp.clientviplevel')),
            ],
            options={
                'verbose_name': 'Topshiriq',
                'verbose_name_plural': 'Topshiriqlar',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='RewardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='client_erp/rewards/')),
                ('reward_type', models.CharField(choices=[('coupon', 'Chegirma kuponi'), ('delivery', 'Bepul yetkazish'), ('gift', "Jismoniy sovg'a"), ('service', 'Bepul xizmat')], default='coupon', max_length=20)),
                ('coin_price', models.IntegerField(verbose_name='Tanga narxi')),
                ('discount_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name="Kupon qiymati (so'm)")),
                ('stock', models.IntegerField(default=0, verbose_name='Zaxira (0=cheksiz)')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('min_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_erp.clientviplevel', verbose_name='Min daraja')),
            ],
            options={
                'verbose_name': "Sovg'a",
                'verbose_name_plural': "Sovg'alar",
                'ordering': ['sort_order', 'coin_price'],
            },
        ),
        migrations.CreateModel(
            name='RewardClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins_spent', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('delivered', 'Berildi'), ('cancelled', 'Bekor')], default='pending', max_length=20)),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_claims', to='client_erp.clientuser')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='client_erp.rewarditem')),
            ],
            options={
                'ordering': ['-claimed_at'],
            },
        ),
        migrations.CreateModel(
            name='XPTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp_change', models.IntegerField(default=0)),
                ('coin_change', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_erp.gamificationrule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_transactions', to='client_erp.clientuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('attended', models.BooleanField(default=False, verbose_name='Keldi (QR tasdiqlangan)')),
                ('attended_at', models.DateTimeField(blank=True, null=True)),
                ('xp_awarded', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='client_erp.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to='client_erp.clientuser')),
            ],
            options={
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='Oy (1-kuni)')),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Chegirma %')),
                ('bonus_coins', models.IntegerField(default=0, verbose_name="Qo'shimcha tanga")),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='Izoh')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vip_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_discounts', to='client_erp.clientviplevel', verbose_name='Daraja')),
            ],
            options={
                'verbose_name': 'Oylik chegirma',
                'verbose_name_plural': 'Oylik chegirmalar',
                'ordering': ['-month', 'vip_level'],
                'unique_together': {('month', 'vip_level')},
            },
        ),
        migrations.CreateModel(
            name='QuestCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0, verbose_name='Bajarilgan soni')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('xp_awarded', models.BooleanField(default=False)),
                ('date', models.DateField(verbose_name='Qaysi kun uchun')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='client_erp.quest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_completions', to='client_erp.clientuser')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'quest', 'date')},
            },
        ),
    ]
