# Generated by Django 5.1.7 on 2026-05-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0002_gamification_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfinancerecord',
            name='category',
            field=models.CharField(blank=True, choices=[('material', 'Material'), ('service', 'Xizmat'), ('transport', 'Transport'), ('furniture', 'Furnitura'), ('mebelcity', 'MebelCity'), ('other', 'Boshqa')], default='', max_length=20, verbose_name='Kategoriya'),
        ),
        migrations.AddField(
            model_name='clientfinancerecord',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Naqd'), ('card', 'Karta'), ('transfer', "O'tkazma")], default='cash', max_length=20, verbose_name="To'lov usuli"),
        ),
        migrations.AlterField(
            model_name='clientfinancerecord',
            name='record_type',
            field=models.CharField(choices=[('income', 'Kirim'), ('expense', 'Chiqim'), ('withdrawal', 'Pul yechish'), ('debt_given', 'Qarz berdim'), ('debt_received', 'Qarz oldim'), ('debt_paid', "Qarz to'ladi")], max_length=20),
        ),
    ]
