# Generated by Django 5.1.7 on 2026-05-20 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0003_finance_upgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientorder',
            name='overall_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='use_stages',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ClientOrderStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('icon', models.CharField(default='📋', max_length=10)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('sort_order', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('active', 'Faol'), ('completed', 'Tugallangan'), ('skipped', "O'tkazildi")], default='pending', max_length=15)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('is_mebelcity', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_stages', to='client_erp.clientuser')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_stages', to='client_erp.clientuser')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='client_erp.clientorder')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='clientfinancerecord',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='client_erp.clientorderstage'),
        ),
        migrations.CreateModel(
            name='ClientOrderStageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('is_done', models.BooleanField(default=False)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_erp.clientuser')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='client_erp.clientorderstage')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ClientOrderStageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage_templates', to='client_erp.clientuser')),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AddField(
            model_name='clientorder',
            name='stage_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='client_erp.clientorderstagetemplate'),
        ),
        migrations.CreateModel(
            name='ClientOrderStageTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('icon', models.CharField(default='📋', max_length=10)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_mebelcity', models.BooleanField(default=False)),
                ('checklist_json', models.JSONField(blank=True, default=list)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='client_erp.clientorderstagetemplate')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='clientorderstage',
            name='template_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_erp.clientorderstagetemplateitem'),
        ),
        migrations.CreateModel(
            name='ClientOrderPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', "Ko'ruvchi"), ('worker', 'Ishchi'), ('manager', 'Menejer')], default='worker', max_length=10)),
                ('can_add_expense', models.BooleanField(default=False)),
                ('can_complete_stage', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='client_erp.clientorder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_permissions', to='client_erp.clientuser')),
                ('stages', models.ManyToManyField(blank=True, related_name='permitted_users', to='client_erp.clientorderstage')),
            ],
            options={
                'unique_together': {('order', 'user')},
            },
        ),
    ]
