# Generated by Django 5.1.7 on 2026-05-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0004_clientorder_overall_progress_clientorder_use_stages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='action_type',
            field=models.CharField(choices=[('login', 'Ilovaga kirish'), ('purchase', 'Xarid qilish'), ('review', 'Sharh yozish'), ('referral', "Do'st tavsiya"), ('view_products', "Mahsulot ko'rish"), ('share', 'Ulashish'), ('complete_stage', 'Etap tugallash'), ('complete_order', 'Buyurtma tugallash'), ('custom', 'Boshqa')], default='custom', max_length=20),
        ),
    ]
