# Generated by Django 5.1.7 on 2026-05-20 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0005_alter_quest_action_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(default='month', max_length=10)),
                ('analysis_text', models.TextField()),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('coins_spent', models.IntegerField(default=0)),
                ('analytics_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='client_erp.clientuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
