# Generated by Django 5.1.7 on 2026-05-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0006_ai_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientorderstagetemplateitem',
            name='estimated_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clientorderstagetemplateitem',
            name='note',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
