# Generated by Django 5.1.7 on 2026-05-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0007_template_item_note_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfinancerecord',
            name='recipient_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Oluvchi ismi'),
        ),
    ]
