# Generated by Django 5.1.7 on 2026-05-24 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0008_finance_recipient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientloginattempt',
            name='login_type',
            field=models.CharField(choices=[('web', 'Web'), ('telegram', 'Telegram'), ('qr', 'QR kod')], default='web', max_length=10),
        ),
        migrations.AddField(
            model_name='clientloginattempt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_attempts', to='client_erp.clientuser'),
        ),
    ]
