# Generated by Django 5.1.7 on 2026-05-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0009_add_login_type_to_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientorder',
            name='zaklad_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
