# Generated by Django 5.1.7 on 2026-06-01 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0010_add_zaklad_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientfinancerecord',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_records', to='client_erp.clientorder'),
        ),
    ]
