# Generated by Django 5.1.7 on 2026-06-01 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0011_fix_finance_order_cascade'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_teams', to='client_erp.clientuser')),
            ],
        ),
        migrations.CreateModel(
            name='ClientProfitTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profit_templates', to='client_erp.clientteam')),
            ],
        ),
        migrations.CreateModel(
            name='ClientTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Egasi'), ('admin', 'Admin'), ('worker', 'Ishchi'), ('viewer', "Ko'ruvchi")], default='worker', max_length=10)),
                ('profit_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('invited', 'Taklif qilingan'), ('active', 'Faol'), ('blocked', 'Bloklangan')], default='invited', max_length=10)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='client_erp.clientteam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='client_erp.clientuser')),
            ],
            options={
                'unique_together': {('team', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ClientProfitTemplateLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_label', models.CharField(max_length=100)),
                ('percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_remainder', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='client_erp.clientprofittemplate')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_erp.clientteammember')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ClientOrderProfitShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_remainder', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profit_shares', to='client_erp.clientorder')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_erp.clientteammember')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ClientOrderShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.CharField(choices=[('full', "To'liq"), ('limited', 'Cheklangan'), ('finance_hidden', 'Moliya yashirin')], default='full', max_length=20)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_add_expense', models.BooleanField(default=False)),
                ('can_complete', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='client_erp.clientorder')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_erp.clientuser')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_orders', to='client_erp.clientteam')),
            ],
            options={
                'unique_together': {('order', 'team')},
            },
        ),
    ]
