# Generated by Django 5.1.7 on 2026-06-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0013_add_profit_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientorderstage',
            name='mebelcity_order_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
