# Generated by Django 5.1.7 on 2026-06-05 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0014_add_mebelcity_order_id_to_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOrderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='client_erp/files/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='client_erp/files/thumbs/')),
                ('file_type', models.CharField(choices=[('image', 'Rasm'), ('video', 'Video'), ('document', 'Hujjat')], default='document', max_length=10)),
                ('file_name', models.CharField(default='', max_length=300)),
                ('file_size', models.BigIntegerField(default=0)),
                ('caption', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='client_erp.clientorder')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to='client_erp.clientuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientOrderNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_notes', to='client_erp.clientuser')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='client_erp.clientorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
