# Generated by Django 5.1.7 on 2026-06-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0015_add_order_files_and_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientorder',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
