# Generated by Django 5.1.7 on 2026-07-07 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0016_clientorder_deleted_at_clientorder_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nomi')),
                ('prompt_text', models.TextField(verbose_name='Prompt matni')),
                ('category', models.CharField(choices=[('color', 'Rang'), ('product', 'Mahsulot'), ('other', 'Boshqa')], default='other', max_length=20)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_base', models.BooleanField(default=False, help_text="Belgilansa — tugma sifatida ko'rinmaydi, lekin matni HAR BIR AI so'roviga (tugma orqalimi, o'zi yozganmi) avtomatik qo'shiladi.", verbose_name='Umumiy standart instruksiya')),
                ('source_product_name', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_presets', to='client_erp.clientuser')),
            ],
            options={
                'verbose_name': 'AI prompt preset',
                'verbose_name_plural': 'AI prompt presetlar',
                'ordering': ['category', 'sort_order', 'id'],
            },
        ),
    ]
