# Generated by Django 5.1.7 on 2026-07-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0017_promptpreset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promptpreset',
            name='category',
            field=models.CharField(choices=[('color', 'Rang'), ('product', 'Mahsulot'), ('style', "Uslub (umumiy, panelda tugma sifatida ko'rinadi)"), ('other', 'Boshqa')], default='other', max_length=20),
        ),
    ]
