# Generated by Django 5.1.7 on 2026-07-07 13:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0018_alter_promptpreset_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('contract_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('terms_text', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('sent', 'Mijozga yuborilgan'), ('confirmed', 'Mijoz tasdiqladi'), ('rejected', 'Mijoz rad etdi'), ('cancelled', 'Bekor qilingan')], default='sent', max_length=15)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('rejection_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to='client_erp.clientuser')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='client_erp.clientorder')),
            ],
            options={
                'verbose_name': 'Mijoz shartnomasi',
                'verbose_name_plural': 'Mijoz shartnomalari',
                'ordering': ['-created_at'],
            },
        ),
    ]
