# Generated by Django 5.1.7 on 2026-07-08 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0019_clientcontract'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientorder',
            name='delete_note',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name="O'chirish sababi"),
        ),
    ]
