# Generated by Django 5.1.7 on 2026-07-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0020_clientorder_delete_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOrderStatusDef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=30, unique=True)),
                ('label', models.CharField(max_length=50)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, verbose_name="Filterda ko'rinadimi")),
                ('is_system', models.BooleanField(default=False, verbose_name="Tizim statusi (key o'zgarmas)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Buyurtma statusi',
                'verbose_name_plural': 'Buyurtma statuslari',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
