# Generated by Django 5.1.7 on 2026-07-08 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0022_seed_order_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='xptransaction',
            name='is_reversed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='xptransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xp_transactions', to='client_erp.clientorder'),
        ),
        migrations.AddField(
            model_name='xptransaction',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xp_transactions', to='client_erp.clientorderstage'),
        ),
        migrations.AlterField(
            model_name='clientorder',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('waiting', 'Kutilmoqda'), ('in_progress', 'Jarayonda'), ('at_mebelcity', 'MebelCity da'), ('ready', 'Tayyor'), ('delivered', 'Topshirildi'), ('cancelled', 'Bekor')], default='new', max_length=20),
        ),
    ]
