# Generated by Django 5.1.7 on 2026-07-09 04:31

import django.db.models.deletion
from django.db import migrations, models


def _managers_see_money(apps, schema_editor):
    """Mavjud manager ruxsatlariga can_see_money=True (sensible default)."""
    Perm = apps.get_model('client_erp', 'ClientOrderPermission')
    Perm.objects.using(schema_editor.connection.alias).filter(
        role='manager',
    ).update(can_see_money=True)


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0023_xptransaction_is_reversed_xptransaction_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientorderpermission',
            name='can_see_money',
            field=models.BooleanField(default=False, verbose_name="Pul ko'rinadi"),
        ),
        migrations.CreateModel(
            name='ClientStandingShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', "Ko'ruvchi"), ('worker', 'Ishchi'), ('manager', 'Menejer')], default='worker', max_length=10)),
                ('can_add_expense', models.BooleanField(default=False)),
                ('can_complete_stage', models.BooleanField(default=True)),
                ('can_see_money', models.BooleanField(default=False, verbose_name="Pul ko'rinadi")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standing_memberships', to='client_erp.clientuser', verbose_name="A'zo")),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standing_shares', to='client_erp.clientuser', verbose_name='Egasi')),
            ],
            options={
                'unique_together': {('owner', 'member')},
            },
        ),
        migrations.RunPython(_managers_see_money, _noop),
    ]
