# Generated by Django 5.1.7 on 2026-07-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0024_clientorderpermission_can_see_money_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientteam',
            name='auto_can_add_expense',
            field=models.BooleanField(default=False, verbose_name="Avto: chiqim qo'sha oladi"),
        ),
        migrations.AddField(
            model_name='clientteam',
            name='auto_can_complete_stage',
            field=models.BooleanField(default=True, verbose_name='Avto: etap tugata oladi'),
        ),
        migrations.AddField(
            model_name='clientteam',
            name='auto_can_see_money',
            field=models.BooleanField(default=True, verbose_name="Avto: pul ko'rinadi"),
        ),
        migrations.AddField(
            model_name='clientteam',
            name='auto_role',
            field=models.CharField(choices=[('viewer', "Ko'ruvchi"), ('worker', 'Ishchi'), ('manager', 'Menejer')], default='worker', max_length=10, verbose_name='Avto-ruxsat roli'),
        ),
        migrations.AddField(
            model_name='clientteam',
            name='auto_share_new_orders',
            field=models.BooleanField(default=False, verbose_name='Yangi buyurtmalar jamoaga avto-ochilsin'),
        ),
    ]
