# Generated by Django 5.1.7 on 2026-07-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0025_clientteam_auto_can_add_expense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientorder',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
