# Generated by Django 5.1.7 on 2026-07-12 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0026_clientorder_delivered_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('price_uzs', models.BigIntegerField(default=0, verbose_name='Narx (UZS)')),
                ('period_days', models.IntegerField(default=30, verbose_name='Davr (kun)')),
                ('coin_grant', models.IntegerField(default=0, verbose_name='Har davrda beriladigan tanga')),
                ('feature_keys', models.JSONField(blank=True, default=list, help_text="Bo'sh = hammasi ruxsat etilgan", verbose_name='Ruxsat etilgan feature kalitlari')),
                ('ai_included', models.BooleanField(default=False, verbose_name='AI kiritilgan')),
                ('is_free', models.BooleanField(default=False, help_text="Login uchun default tarif — faqat bittasi bo'lishi kerak", verbose_name='Standart (bepul) tarif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('sort', models.IntegerField(default=0, verbose_name='Tartib')),
                ('color', models.CharField(blank=True, default='', max_length=20, verbose_name='Rang')),
                ('icon', models.CharField(blank=True, default='', max_length=20, verbose_name='Emoji/Ikonka')),
                ('description', models.TextField(blank=True, default='', verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mini ERP Tarif',
                'verbose_name_plural': 'Mini ERP Tariflar',
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.AddField(
            model_name='clientuser',
            name='plan_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tarif muddati'),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='plan_since',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tarif boshlangan'),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='client_erp.clientplan', verbose_name='Tarif'),
        ),
        migrations.CreateModel(
            name='ClientSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trial', 'Sinov'), ('active', 'Faol'), ('expired', 'Muddati tugagan'), ('cancelled', 'Bekor qilingan')], default='active', max_length=20, verbose_name='Holat')),
                ('period_start', models.DateTimeField(verbose_name='Davr boshi')),
                ('period_end', models.DateTimeField(verbose_name='Davr oxiri')),
                ('source', models.CharField(blank=True, default='', help_text="'admin' | 'trial' | to'lov id", max_length=50, verbose_name='Manba')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='client_erp.clientplan', verbose_name='Tarif')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='client_erp.clientuser', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Mini ERP Obuna',
                'verbose_name_plural': 'Mini ERP Obunalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
