# Generated by Django 5.1.7 on 2026-07-12 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0027_clientplan_clientuser_plan_expires_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAIPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_key', models.CharField(help_text="'analytics_ai','ai_image','ai_panorama','laylo_chat','gemini_live'", max_length=50, unique=True, verbose_name='Amal kodi')),
                ('label', models.CharField(blank=True, default='', max_length=100, verbose_name='Nomi')),
                ('coin_cost', models.IntegerField(default=0, verbose_name='Tanga narxi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol (False => bu funksiya tekin)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI tanga narxi',
                'verbose_name_plural': 'AI tanga narxlari',
                'ordering': ['action_key'],
            },
        ),
        migrations.CreateModel(
            name='CoinPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('coins', models.IntegerField(verbose_name='Asosiy tanga')),
                ('bonus_coins', models.IntegerField(default=0, verbose_name='Bonus tanga')),
                ('price_uzs', models.BigIntegerField(verbose_name='Narx (UZS)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('sort', models.IntegerField(default=0)),
                ('color', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tanga paketi',
                'verbose_name_plural': 'Tanga paketlari',
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CoinLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('purchase', 'Sotib olish'), ('spend', 'Sarflash'), ('grant', 'Berildi (admin)'), ('refund', 'Qaytarish')], max_length=20)),
                ('amount', models.IntegerField(verbose_name='Miqdor (+ kirim / - chiqim)')),
                ('balance_after', models.IntegerField(default=0, verbose_name='Qoldiq')),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('ref_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_ledger', to='client_erp.clientuser')),
            ],
            options={
                'verbose_name': 'Tanga harakati',
                'verbose_name_plural': 'Tanga harakatlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
