# Generated by Django 5.1.7 on 2026-07-12 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0028_clientaiprice_coinpack_coinledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('payme', 'Payme'), ('click', 'Click'), ('octobank', 'Octobank'), ('multicard', 'Multicard'), ('sandbox', 'Sandbox')], max_length=20)),
                ('purpose', models.CharField(choices=[('coin_topup', "Tanga to'ldirish"), ('plan_purchase', 'Tarif sotib olish')], max_length=20)),
                ('target_id', models.IntegerField(default=0, verbose_name='CoinPack.id yoki ClientPlan.id')),
                ('amount_uzs', models.BigIntegerField(default=0, verbose_name='Summa (UZS)')),
                ('status', models.CharField(choices=[('created', 'Yaratildi'), ('pending', 'Kutilmoqda'), ('paid', "To'landi"), ('failed', 'Muvaffaqiyatsiz'), ('cancelled', 'Bekor qilindi')], db_index=True, default='created', max_length=20)),
                ('external_id', models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='Provider tranzaksiya ID')),
                ('checkout_url', models.TextField(blank=True, default='')),
                ('fulfilled', models.BooleanField(default=False, verbose_name='Bajarildi (tanga berildi / tarif tayinlandi)')),
                ('raw', models.JSONField(blank=True, default=dict, verbose_name='Provider javoblari (audit)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='client_erp.clientuser')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(default=False)),
                ('error_code', models.CharField(blank=True, default='', max_length=40)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='client_erp.clientpayment')),
            ],
            options={
                'verbose_name': "To'lov urinishi",
                'verbose_name_plural': "To'lov urinishlari",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='payme', max_length=20)),
                ('token', models.TextField(verbose_name="Shifrlangan token (F3'da oddiy saqlanadi)")),
                ('card_masked', models.CharField(blank=True, default='', max_length=24)),
                ('expire', models.CharField(blank=True, default='', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_cards', to='client_erp.clientuser')),
            ],
            options={
                'verbose_name': 'Saqlangan karta',
                'verbose_name_plural': 'Saqlangan kartalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
