# Generated by Django 5.1.7 on 2026-07-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0029_clientpayment_paymentattempt_savedcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientplan',
            name='limits',
            field=models.JSONField(blank=True, default=dict, help_text="{limit_kaliti: son}. Kalit yo'q yoki manfiy (-1) = CHEKSIZ. Masalan {'orders_month': 15, 'customers': 50, 'team_members': 1}", verbose_name='Miqdoriy limitlar'),
        ),
    ]
