# Generated by Django 5.1.7 on 2026-07-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0030_clientplan_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='oferta_accepted',
            field=models.BooleanField(default=False, verbose_name='Ofertani qabul qilgan'),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='oferta_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Oferta qabul sanasi'),
        ),
    ]
