# Generated by Django 5.1.7 on 2026-07-14 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0031_clientuser_oferta_accepted_and_more'),
        ('products', '0006_product_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFeaturedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('sold_qty_30d', models.DecimalField(decimal_places=4, default=0, help_text="Tanlangan paytdagi so'nggi 30 kunlik sotuv miqdori (ma'lumot uchun)", max_digits=18)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_entries', to='products.product')),
            ],
            options={
                'verbose_name': 'Vitrina mahsuloti',
                'verbose_name_plural': 'Vitrina mahsulotlari',
                'ordering': ['added_at'],
            },
        ),
    ]
