# Generated by Django 5.1.7 on 2026-07-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0032_clientfeaturedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientorder',
            name='share_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True, verbose_name='Mijoz ulashish UUID'),
        ),
    ]
