# Generated by Django 5.1.7 on 2026-07-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0033_clientorder_share_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='expense_categories',
            field=models.JSONField(blank=True, default=list, verbose_name='Chiqim kategoriyalari'),
        ),
    ]
