# Generated by Django 5.1.7 on 2026-07-15 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0034_clientuser_expense_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymeMerchantTxn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payme_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Payme tranzaksiya id (params.id)')),
                ('amount_tiyin', models.BigIntegerField(default=0)),
                ('state', models.IntegerField(db_index=True, default=1)),
                ('reason', models.IntegerField(blank=True, null=True, verbose_name='Bekor sababi')),
                ('create_time', models.BigIntegerField(default=0)),
                ('perform_time', models.BigIntegerField(default=0)),
                ('cancel_time', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payme_txns', to='client_erp.clientpayment')),
            ],
            options={
                'verbose_name': 'Payme tranzaksiya (kassa)',
                'verbose_name_plural': 'Payme tranzaksiyalar (kassa)',
                'ordering': ['-created_at'],
            },
        ),
    ]
