# Generated by Django 5.1.7 on 2026-07-31 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0035_paymemerchanttxn'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfitPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Usta ismi')),
                ('is_active', models.BooleanField(default=True, help_text="O'chirilsa — arxiv: ro'yxatda ham, hisobotda ham ko'rinmaydi", verbose_name='Faol')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profit_people', to='client_erp.clientuser', verbose_name='Akkaunt')),
            ],
            options={
                'verbose_name': "Usta (foyda ro'yxati)",
                'verbose_name_plural': "Ustalar ro'yxati",
                'ordering': ['sort_order', 'id'],
                'unique_together': {('owner', 'name')},
            },
        ),
    ]
