# Generated by Django 5.1.7 on 2026-08-04 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0037_profit_withdrawal_line_user_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientMonthEndReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='month_end_reminders', to='client_erp.clientuser')),
            ],
            options={
                'unique_together': {('owner', 'year', 'month')},
            },
        ),
    ]
