# Generated by Django 5.1.7 on 2026-08-04 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0038_month_end_reminder_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfinancerecord',
            name='is_reversal',
            field=models.BooleanField(default=False, verbose_name='Bekor qilish yozuvi'),
        ),
        migrations.AddField(
            model_name='clientfinancerecord',
            name='source_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_records', to='client_erp.clientprofitwithdrawalline', verbose_name='Manba: foyda-yechish qatori'),
        ),
        migrations.AddField(
            model_name='clientprofitwithdrawal',
            name='client_request_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True, verbose_name="Mijoz so'rov ID (takrorlanishga qarshi)"),
        ),
        migrations.AddField(
            model_name='clientprofitwithdrawal',
            name='reverse_note',
            field=models.TextField(blank=True, default='', verbose_name='Bekor qilish sababi'),
        ),
        migrations.AddField(
            model_name='clientprofitwithdrawal',
            name='reversed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofitwithdrawal',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_withdrawals', to='client_erp.clientuser'),
        ),
        migrations.AlterField(
            model_name='clientprofitwithdrawal',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('confirmed', 'Tasdiqlangan'), ('completed', 'Yechilgan'), ('reversed', 'Bekor qilingan')], default='pending', max_length=10),
        ),
    ]
