# Generated by Django 5.1.7 on 2026-08-04 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0039_clientfinancerecord_is_reversal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientorderprofitshare',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profit_shares', to='client_erp.clientuser', verbose_name="Kontakt (ro'yxatdan o'tgan foydalanuvchi)"),
        ),
    ]
