# Generated by Django 5.1.7 on 2026-08-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0040_clientorderprofitshare_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientnotification',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name="Summa (kartada katta ko'rsatiladi)"),
        ),
        migrations.AddField(
            model_name='clientnotification',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='Ikonka (emoji)'),
        ),
        migrations.AddField(
            model_name='clientnotification',
            name='link',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name="Bosilganda o'tadigan sahifa (SPA yo'li)"),
        ),
    ]
