# Generated by Django 5.1.7 on 2026-08-05 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0041_clientnotification_amount_clientnotification_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAiUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('live', 'Ovozli (Gemini Live)'), ('chat', 'Matnli chat'), ('image', 'Rasm'), ('other', 'Boshqa')], db_index=True, default='chat', max_length=16)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_sec', models.IntegerField(default=0, verbose_name='Davomiylik (soniya)')),
                ('audio_ms_in', models.IntegerField(default=0, verbose_name='Yuborilgan audio (ms)')),
                ('tokens_in', models.IntegerField(default=0)),
                ('tokens_out', models.IntegerField(default=0)),
                ('tokens_estimated', models.BooleanField(default=False, verbose_name='Token taxminiy (provayder bermadi)')),
                ('provider', models.CharField(blank=True, default='', max_length=40)),
                ('model_name', models.CharField(blank=True, default='', max_length=80)),
                ('coins_charged', models.IntegerField(default=0)),
                ('charge_reason', models.CharField(blank=True, default='', max_length=24)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage', to='client_erp.clientuser')),
            ],
            options={
                'verbose_name': 'AI foydalanish',
                'verbose_name_plural': 'AI foydalanish',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', 'started_at'], name='client_erp__user_id_9c3cc0_idx')],
            },
        ),
    ]
