# Generated by Django 5.1.7 on 2026-08-06 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0042_clientaiusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfitAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_id', models.IntegerField(blank=True, null=True, verbose_name='Ulush yozuvi id')),
                ('action', models.CharField(choices=[('create', 'Yaratildi'), ('update', "O'zgartirildi"), ('delete', "O'chirildi"), ('link', "Akkauntga bog'landi"), ('share', 'Zakaz ulashildi')], db_index=True, max_length=16)),
                ('actor_note', models.CharField(blank=True, default='', max_length=120)),
                ('target_name', models.CharField(blank=True, default='', max_length=200)),
                ('old_value', models.CharField(blank=True, default='', max_length=200)),
                ('new_value', models.CharField(blank=True, default='', max_length=200)),
                ('reason', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profit_audit_actions', to='client_erp.clientuser')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profit_audit', to='client_erp.clientorder')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profit_audit_received', to='client_erp.clientuser')),
            ],
            options={
                'verbose_name': 'Ulush audit yozuvi',
                'verbose_name_plural': 'Ulush audit jurnali',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', 'created_at'], name='client_erp__order_i_ab2cb3_idx')],
            },
        ),
    ]
