# Generated by Django 5.1.7 on 2026-08-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0043_clientprofitaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfinancerecord',
            name='dup_reviewed',
            field=models.BooleanField(db_index=True, default=False, verbose_name="Dublikat tekshiruvidan o'tgan"),
        ),
    ]
