# Generated by Django 5.1.7 on 2026-08-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0044_clientfinancerecord_dup_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='language',
            field=models.CharField(choices=[('uz', "O'zbekcha"), ('ru', 'Русский'), ('en', 'English')], default='uz', max_length=2, verbose_name='Interfeys tili'),
        ),
    ]
