# Generated by Django 5.1.7 on 2026-08-12 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0047_db_defaults_all_notnull'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='balance_cutover_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name="Balans-kesim boshlang'ich summasi"),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='balance_cutover_date',
            field=models.DateField(blank=True, null=True, verbose_name='Balans-kesim sanasi'),
        ),
        migrations.CreateModel(
            name='ClientFinanceMonthArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ym', models.CharField(max_length=7, verbose_name='Oy (YYYY-MM)')),
                ('finance_snapshot', models.JSONField(verbose_name='Moliya sahifasi natijasi')),
                ('analytics_snapshot', models.JSONField(verbose_name='Analitika sahifasi natijasi')),
                ('frozen_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_month_archives', to='client_erp.clientuser')),
            ],
            options={
                'verbose_name': 'Moliya oy-arxivi',
                'verbose_name_plural': 'Moliya oy-arxivlari',
                'ordering': ['-ym'],
                'unique_together': {('owner', 'ym')},
            },
        ),
    ]
