# Generated by Django 5.1.7 on 2026-08-14 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0048_clientuser_balance_cutover_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zamer_id', models.IntegerField(blank=True, null=True)),
                ('room_name', models.CharField(blank=True, default='', max_length=100)),
                ('height_mm', models.IntegerField(default=2700)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_captures', to='client_erp.clientuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomWallSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=1)),
                ('length_mm', models.IntegerField()),
                ('order', models.IntegerField(default=0)),
                ('source', models.CharField(choices=[('ble', 'BLE lazer'), ('manual', "Qo'lda")], default='manual', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='client_erp.roomcapture')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
