# Generated by Django 5.1.7 on 2026-08-14 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0049_roomcapture_roomwallsegment'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcapture',
            name='depth_mm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomcapture',
            name='width_mm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PlacedModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('catalog', 'Katalog'), ('upload', 'Fayldan')], default='catalog', max_length=10)),
                ('furniture_module_id', models.IntegerField(blank=True, null=True)),
                ('width_mm', models.FloatField()),
                ('height_mm', models.FloatField()),
                ('depth_mm', models.FloatField()),
                ('category', models.CharField(blank=True, default='', max_length=30)),
                ('px', models.FloatField()),
                ('py', models.FloatField()),
                ('scale_f', models.FloatField(default=1)),
                ('mesh_parts', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placed_modules', to='client_erp.roomcapture')),
            ],
        ),
    ]
