# Generated by Django 5.1.7 on 2026-08-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0050_roomcapture_depth_mm_roomcapture_width_mm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placedmodule',
            name='rot_deg',
            field=models.FloatField(default=0),
        ),
    ]
