# Generated by Django 5.1.7 on 2026-08-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0051_placedmodule_rot_deg'),
    ]

    operations = [
        migrations.AddField(
            model_name='placedmodule',
            name='rot_x_deg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='placedmodule',
            name='rot_z_deg',
            field=models.FloatField(default=0),
        ),
    ]
