# Generated by Django 5.1.7 on 2026-08-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0052_placedmodule_rot_x_deg_placedmodule_rot_z_deg'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcapture',
            name='finish',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
