# Generated by Django 5.1.7 on 2026-08-15 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0053_roomcapture_finish'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSupplierDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditor_name', models.CharField(max_length=150)),
                ('creditor_type', models.CharField(choices=[('dokon', "Do'kon"), ('ustanovchik', 'Ustanovchik'), ('shaxs', 'Shaxs'), ('boshqa', 'Boshqa')], default='dokon', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('paid', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_debts', to='client_erp.clientorder')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_debts', to='client_erp.clientuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
