# Generated by Django 5.1.7 on 2026-08-15 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0054_clientsupplierdebt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOrderExpenseShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('is_payer', models.BooleanField(default=False, verbose_name="Pulni fizik to'lagan")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('debt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_shares', to='client_erp.clientsupplierdebt')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_shares', to='client_erp.clientorder')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_shares', to='client_erp.clientfinancerecord')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_shares', to='client_erp.clientuser')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
                'indexes': [models.Index(fields=['order', 'user'], name='client_erp__order_i_313eb4_idx')],
            },
        ),
    ]
