# Generated by Django 5.1.7 on 2026-08-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0055_clientorderexpenseshare'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsupplierdebt',
            name='taken_date',
            field=models.DateField(blank=True, null=True, verbose_name='Qachon olingan'),
        ),
        migrations.AlterField(
            model_name='clientprofitaudit',
            name='action',
            field=models.CharField(choices=[('create', 'Yaratildi'), ('update', "O'zgartirildi"), ('delete', "O'chirildi"), ('link', "Akkauntga bog'landi"), ('share', 'Zakaz ulashildi'), ('unshare', 'Sherik chiqarildi')], db_index=True, max_length=16),
        ),
    ]
