# Generated by Django 5.1.7 on 2026-08-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0056_clientsupplierdebt_taken_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placedmodule',
            name='color',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='placedmodule',
            name='is_wall_item',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='placedmodule',
            name='part_label',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
