# Generated by Django 5.1.7 on 2026-08-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0057_placedmodule_color_placedmodule_is_wall_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placedmodule',
            name='source',
            field=models.CharField(choices=[('catalog', 'Katalog'), ('upload', 'Fayldan'), ('wall', 'Devor jihozi')], default='catalog', max_length=10),
        ),
    ]
