# Generated by Django 5.1.7 on 2026-08-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0058_alter_placedmodule_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='placedmodule',
            name='home_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placedmodule',
            name='home_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placedmodule',
            name='home_z',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placedmodule',
            name='pz',
            field=models.FloatField(default=0),
        ),
    ]
