# Generated by Django 5.1.7 on 2026-08-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0059_placedmodule_home_x_placedmodule_home_y_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcapture',
            name='openings',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomcapture',
            name='outline',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
