# Generated by Django 5.1.7 on 2026-08-18 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0060_roomcapture_openings_roomcapture_outline'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomPlanImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zamer_id', models.IntegerField(blank=True, null=True)),
                ('room_id', models.IntegerField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('image', 'Rasm'), ('pdf', 'PDF'), ('dxf', 'DXF/AutoCAD'), ('b3d', 'Bazis .b3d')], default='image', max_length=10)),
                ('source_file', models.FileField(upload_to='room_plans/%Y/%m/')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='room_plans/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Navbatda'), ('running', 'Ishlanmoqda'), ('done', 'Tayyor'), ('error', 'Xato')], default='pending', max_length=10)),
                ('error_text', models.TextField(blank=True, default='')),
                ('result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('client_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_imports', to='client_erp.clientuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
