# Generated by Django 5.1.7 on 2026-08-24 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0061_roomplanimport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=64)),
                ('kind', models.CharField(choices=[('js', 'JS xatosi'), ('promise', 'Ushlanmagan promise'), ('fetch', "So'rov xatosi"), ('ws', 'WebSocket'), ('ble', 'Bluetooth / lazer'), ('media', 'Kamera / fayl'), ('console', 'console.error'), ('manual', "Qo'lda yuborilgan")], db_index=True, default='js', max_length=12)),
                ('message', models.TextField()),
                ('stack', models.TextField(blank=True, default='')),
                ('page', models.CharField(blank=True, default='', max_length=300)),
                ('source', models.CharField(blank=True, default='', max_length=300)),
                ('req_url', models.CharField(blank=True, default='', max_length=300)),
                ('req_status', models.IntegerField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('platform', models.CharField(blank=True, default='', max_length=60)),
                ('screen', models.CharField(blank=True, default='', max_length=32)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('fingerprint', models.CharField(db_index=True, max_length=40)),
                ('count', models.IntegerField(default=1)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
                ('client_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_logs', to='client_erp.clientuser')),
            ],
            options={
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['-last_seen', 'is_resolved'], name='client_erp__last_se_271647_idx')],
            },
        ),
    ]
