# Generated by Django 5.1.7 on 2026-09-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0062_clienterrorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientorder',
            name='ready_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
