# Generated by Django 5.1.7 on 2026-09-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0063_clientorder_ready_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientorderfile',
            name='external_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='clientorderfile',
            name='file',
            field=models.FileField(blank=True, upload_to='client_erp/files/'),
        ),
        migrations.AlterField(
            model_name='clientorderfile',
            name='file_type',
            field=models.CharField(choices=[('image', 'Rasm'), ('video', 'Video'), ('document', 'Hujjat'), ('link', 'Havola')], default='document', max_length=10),
        ),
    ]
