# Generated by Django 5.1.7 on 2026-09-04 09:51

import client_erp.models.detal_qr
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0064_clientorderfile_external_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDetalCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_code', models.CharField(db_index=True, default=client_erp.models.detal_qr._gen_short_code, max_length=16, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('artikul', models.CharField(blank=True, default='', max_length=100)),
                ('detal_count', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='client_erp/detal_qr/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detal_cards', to='client_erp.clientorder')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detal_cards', to='client_erp.clientuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
