# Generated by Django 5.1.7 on 2026-09-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0065_clientdetalcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('view', 'HTTP view xatosi'), ('render', '.b3d / rasm render'), ('parser', 'Fayl parslash'), ('ws', 'WebSocket handler'), ('worker', 'Fon jarayon / worker'), ('external', 'Tashqi API/servis'), ('other', 'Boshqa')], db_index=True, default='other', max_length=12)),
                ('message', models.TextField()),
                ('traceback', models.TextField(blank=True, default='')),
                ('source', models.CharField(blank=True, default='', max_length=300)),
                ('username', models.CharField(blank=True, default='', max_length=64)),
                ('request_path', models.CharField(blank=True, default='', max_length=300)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('fingerprint', models.CharField(db_index=True, max_length=40)),
                ('count', models.IntegerField(default=1)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['-last_seen', 'is_resolved'], name='client_erp__last_se_eafb42_idx')],
            },
        ),
    ]
