# Generated by Django 5.1.7 on 2026-09-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0066_servererrorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetalcard',
            name='panel_data',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
