# Generated by Django 5.1.7 on 2026-09-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_erp', '0067_clientdetalcard_panel_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientorderfile',
            name='measurements',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
